# Medium Tests: Run on all commits/PRs to dev branch

language: c
sudo: required
dist: trusty
matrix:
  include:
    # Container
    - sudo: false
      env: Cmd='make check'

    - env: Cmd='make arminstall && make armfuzz'

    # tag-specific test
    - if: tag =~ ^v[0-9]\.[0-9]
      sudo: false
      env: Cmd='make -C tests checkTag && tests/checkTag $TRAVIS_BRANCH'

git:
  depth: 1

script:
  - JOB_NUMBER=$(echo $TRAVIS_JOB_NUMBER | sed -e 's:[0-9][0-9]*\.\(.*\):\1:')
  - echo JOB_NUMBER=$JOB_NUMBER TRAVIS_BRANCH=$TRAVIS_BRANCH TRAVIS_EVENT_TYPE=$TRAVIS_EVENT_TYPE TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST
  - export FUZZERTEST=-T2mn;
    export ZSTREAM_TESTTIME=-T2mn;
    export DECODECORPUS_TESTTIME=-T1mn;
    sh -c "$Cmd" || travis_terminate 1;
